name: CI

on:
  push:

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2

      - name: Use Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 19

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Format
        run: npx prettier --check src
